[package]
name = "changeset-component-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
quick-xml = { version = "0.39.0", features = ["serde", "serialize"] }
serde = { version = "1.0.228", features = ["derive"] }
tabled = "0.20.0"
